export const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

export const PALETTE = {
  navyDark: "#1c1e44",
  navyMid: "#2b2f54",
  cream: "#F5F6DB",
  navyTint: "#3a3e6e",
  white: "#FFFFFF",
};

export const RISK_META = {
  SAFE: { color: "#7ee2a8", bg: "#7ee2a822", Icon: null },
  LOW: { color: "#ffd166", bg: "#ffd16622", Icon: null },
  HIGH: { color: "#ff9f68", bg: "#ff9f6822", Icon: null },
  CRITICAL: { color: "#ff6b6b", bg: "#ff6b6b22", Icon: null },
};

export const STATUS_OPTIONS = ["pending", "confirmed scam", "likely safe", "needs investigation", "escalated"];

export const STRINGS = {
  en: {
    appName: "CyberKavach",
    tagline: "Pre-transaction fraud shield",
    elderlyMode: "Elderly mode",
    language: "Language",
    homeTitle: "Check a payment before you approve it",
    homeSubtitle: "Paste a UPI link, scan a QR code, or enter a UPI ID. CyberKavach reviews the request and explains the risk before you enter your PIN.",
    checkButton: "Check a payment",
    demoLabel: "For this demonstration, choose a risk level to preview how CyberKavach responds.",
    demoTitle: "Preview a result",
    emergencyButton: "Emergency: call 1930",
    back: "Back",
    hearAgain: "Hear this again",
    callNow: "Call 1930 now",
    getHelp: "Ask someone for help",
    getHelpNowTitle: "Get help now",
    call1930: "Call 1930",
    helpline: "National Cyber Crime Helpline",
    askFamily: "Ask a trusted family member",
    voiceLang: "en-IN",
    pasteLabel: "Paste the payment link or QR text",
    pastePlaceholder: "e.g. upi://pay?pa=name@bank&am=500",
    checkThisPayment: "Check this payment",
    checking: "Checking your payment…",
    checkError: "We could not check this payment right now. Please try again.",
    scamCategoryLabel: "Type of scam",
    amountLabel: "Amount",
    payeeLabel: "Paying to",
    riskScoreLabel: "Risk score",
    recommendedActionLabel: "Recommended action",
    riskIndicatorsTitle: "Why this was flagged",
    adviceTitle: "What you should do",
    reportButton: "Report this to protect others",
    reportSending: "Sending your report…",
    reportSent: "Report received. Thank you for helping keep others safe.",
    notPayButton: "I chose not to pay",
    notPayConfirmed: "Recorded. Thank you for staying safe.",
    activeAlertTitle: "Active scam alert",
    trustLine: "No sign-in. No phone number. Reports stay anonymous.",
    risk: {
      SAFE: { label: "Safe", message: "This payment request does not show signs of fraud. You may proceed with normal caution.", voice: "This looks safe. You may continue." },
      LOW: { label: "Ask someone for help", message: "This request has a few unusual details. Show it to a family member before you pay.", voice: "This might be risky. Please ask a family member or friend before you pay." },
      HIGH: { label: "Do not pay. Verify first", message: "Do not pay yet. Call the person or company directly to confirm the request before paying.", voice: "Do not pay yet. Please call the person directly to check before you pay." },
      CRITICAL: { label: "Dangerous request", message: "Do not pay. This request matches known scam patterns.", voice: "Warning. This may be a scam. Do not pay. Do not share your O T P, PIN, or password." },
    },
  },
  hi: {
    appName: "CyberKavach",
    tagline: "भुगतान से पहले सुरक्षा जांच",
    elderlyMode: "बुजुर्ग मोड",
    language: "भाषा",
    homeTitle: "भुगतान स्वीकार करने से पहले उसकी जांच करें",
    homeSubtitle: "यूपीआई लिंक पेस्ट करें, क्यूआर कोड स्कैन करें, या यूपीआई आईडी दर्ज करें। CyberKavach अनुरोध की जांच करता है और पिन डालने से पहले जोखिम बताता है।",
    checkButton: "भुगतान जांचें",
    demoLabel: "इस प्रदर्शन के लिए, यह देखने हेतु कोई जोखिम स्तर चुनें कि CyberKavach कैसे प्रतिक्रिया देता है।",
    demoTitle: "परिणाम का पूर्वावलोकन",
    emergencyButton: "आपातकाल: 1930 पर कॉल करें",
    back: "वापस",
    hearAgain: "फिर से सुनें",
    callNow: "अभी 1930 पर कॉल करें",
    getHelp: "किसी से मदद लें",
    getHelpNowTitle: "अभी मदद लें",
    call1930: "1930 पर कॉल करें",
    helpline: "राष्ट्रीय साइबर अपराध हेल्पलाइन",
    askFamily: "परिवार के किसी विश्वसनीय सदस्य से पूछें",
    voiceLang: "hi-IN",
    pasteLabel: "भुगतान लिंक या क्यूआर टेक्स्ट पेस्ट करें",
    pastePlaceholder: "उदाहरण: upi://pay?pa=name@bank&am=500",
    checkThisPayment: "इस भुगतान की जांच करें",
    checking: "आपके भुगतान की जांच हो रही है…",
    checkError: "अभी जांच नहीं हो सकी। कृपया दोबारा प्रयास करें।",
    scamCategoryLabel: "धोखाधड़ी का प्रकार",
    amountLabel: "राशि",
    payeeLabel: "किसे भुगतान",
    riskScoreLabel: "जोखिम स्कोर",
    recommendedActionLabel: "अनुशंसित कार्रवाई",
    riskIndicatorsTitle: "यह क्यों चिह्नित हुआ",
    adviceTitle: "आपको क्या करना चाहिए",
    reportButton: "दूसरों की सुरक्षा हेतु रिपोर्ट करें",
    reportSending: "रिपोर्ट भेजी जा रही है…",
    reportSent: "रिपोर्ट प्राप्त हुई। सुरक्षित रहने में मदद के लिए धन्यवाद।",
    notPayButton: "मैंने भुगतान नहीं किया",
    notPayConfirmed: "दर्ज कर लिया गया। सुरक्षित रहने के लिए धन्यवाद।",
    activeAlertTitle: "सक्रिय धोखाधड़ी चेतावनी",
    trustLine: "कोई साइन-इन नहीं। कोई फ़ोन नंबर नहीं। रिपोर्ट गुमनाम रहती हैं।",
    risk: {
      SAFE: { label: "सुरक्षित", message: "इस भुगतान अनुरोध में धोखाधड़ी के लक्षण नहीं दिखे। सामान्य सावधानी के साथ आगे बढ़ें।", voice: "यह सुरक्षित लगता है। आप आगे बढ़ सकते हैं।" },
      LOW: { label: "किसी से मदद मांगें", message: "इस अनुरोध में कुछ असामान्य विवरण हैं। भुगतान से पहले परिवार के किसी सदस्य को दिखाएं।", voice: "इसमें जोखिम हो सकता है। कृपया भुगतान करने से पहले परिवार के किसी सदस्य या दोस्त से पूछें।" },
      HIGH: { label: "भुगतान न करें, पहले जांचें", message: "अभी भुगतान न करें। भुगतान से पहले व्यक्ति या कंपनी को सीधे कॉल कर पुष्टि करें।", voice: "अभी भुगतान न करें। कृपया भुगतान करने से पहले सीधे व्यक्ति को कॉल करके जांच लें।" },
      CRITICAL: { label: "खतरनाक अनुरोध", message: "भुगतान न करें। यह अनुरोध ज्ञात धोखाधड़ी पैटर्न से मेल खाता है।", voice: "चेतावनी। यह धोखाधड़ी हो सकती है। भुगतान न करें। अपना ओटीपी, पिन या पासवर्ड किसी को न बताएं।" },
    },
  },
};